### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by JedWalton** [stefanogali/panic-panini-next#1]
Hi,

This is great template and I would love to contribute and build on top of this.

However, I would need to add the MIT licence to be able to work with this!

Jed

**Comment by stefanogali** [comment]
Hello Jed,

glad you like the template!

Thanks for the license I missed it, PR is merged...feel free to contribute.

Cheers
Stefano

**Comment by JedWalton** [comment]
Thanks for Merging the PR. 

It would be really cool to make it work for multiple bands all from a unified template.

What is your vision for the future the project?

Cheers
Jed

**Comment by stefanogali** [comment]
Hi Jed

I was thinking to add an integration with an headless CMS, probably WordPress or Strapi, to make content changes. Also would like to add some internal pages.

Yeah it would be cool to make the template work for bands of different genres, feel free to develop your ideas further on a new branch if you wish.

Cheers
Stefano
